consumes:
- application/json
definitions:
  models.Address:
    properties:
      email:
        type: string
      first-name:
        type: string
      id:
        type: integer
      last-name:
        type: string
      phone:
        type: string
    required:
    - email
    - first-name
    - last-name
    - phone
    type: object
info:
  contact:
    email: Johannes.Hoehne1@mail.schwarz
    name: Johannes Höhne
  description: This is a simple GO application with some basic REST CRUD operations.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: GO Example Addressbook
  version: "1.0"
paths:
  /addresses:
    delete:
      description: Will delete all addresses. an empty list will be returned
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Delete all addresses
      tags:
      - addresses
    get:
      description: Provide a list of all currently known addresses
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Address'
            type: array
      summary: List all addresses
      tags:
      - addresses
    post:
      consumes:
      - application/json
      description: Will add a new addresses entity to the storage. The new created
        addresses will be returned. Don't add the Id to the addresses parameter
      parameters:
      - description: The new addresses without ID
        in: body
        name: addresses
        required: true
        schema:
          $ref: '#/definitions/models.Address'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: ID must be zero, Unparsable JSON body
          schema:
            type: string
      summary: Add a new addresses
      tags:
      - addresses
  /addresses/{id}:
    delete:
      description: Delete a address with the provided ID
      parameters:
      - description: ID of the address
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Unknown ID
          schema:
            type: string
      summary: Delete one address
      tags:
      - addresses
    get:
      description: Get a address with the provided ID
      parameters:
      - description: ID of the user
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Address'
        "400":
          description: Unknown ID
          schema:
            type: string
      summary: Get one address
      tags:
      - addresses
    put:
      consumes:
      - application/json
      description: Will update an existing address which is identified via its ID
      parameters:
      - description: ID of the address
        in: path
        name: id
        required: true
        type: integer
      - description: The new address without ID
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.Address'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Address'
        "400":
          description: Unknown ID, ID miss match, Unparsable JSON body
          schema:
            type: string
      summary: Update an existing address
      tags:
      - addresses
  /metrics:
    get:
      description: Provide a list of all currently known Prometheus metrics
      produces:
      - text/plain
      responses:
        "200":
          description: Prometheus metrics line by line
          schema:
            type: string
      summary: List all Prometheus metrics
      tags:
      - metrics
produces:
- application/json
swagger: "2.0"
